name: Build and Release Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            debhelper devscripts dpkg-dev \
            nlohmann-json3-dev lcov curl libcurl4-openssl-dev catch2

      - name: Build with CMake + CPack (with coverage)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DBUILD_EXAMPLES=OFF \
                   -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
          cmake --build . -- -j$(nproc)

      - name: Run tests (Ubuntu)
        run: |
          cd build
          ctest --output-on-failure
        continue-on-error: true

      - name: Generate coverage report (Ubuntu)
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info --ignore-errors source,negative
          lcov --remove coverage.info '/usr/*' 'tests/*' --output-file coverage.info --ignore-errors source,negative
          genhtml coverage.info --output-directory coverage-html
          mkdir -p ../coverage-html/ubuntu
          cp -r coverage-html/* ../coverage-html/ubuntu/

      - name: Package with CPack and Debian policy
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j$(nproc)
          (cd build && cpack -G DEB && cpack -G TGZ)
          ln -s packaging/debian debian
          dpkg-buildpackage -us -uc -b

      - name: Upload Debian artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: ${{ github.workspace }}/*.deb

  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pacman -Syu --noconfirm base-devel git cmake nlohmann-json lcov curl gcc catch2

      - name: Compute SHA256 of release tarball
        run: |
          TAG_NAME=${GITHUB_REF_NAME}  # e.g. v0.1.0
          TAR_NAME="llama-cpp-tools-${TAG_NAME}.tar.gz"
          curl -L -o "$TAR_NAME" \
            "https://github.com/lambroulabs/llama-cpp-tools/archive/refs/tags/${TAG_NAME}.tar.gz"
          SHA=$(sha256sum "$TAR_NAME" | awk '{print $1}')
          sed -i "s/sha256sums=('SKIP')/sha256sums=('${SHA}')/" packaging/arch/PKGBUILD

      - name: Build Arch package (with coverage)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
                   -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
          cmake --build . -- -j$(nproc)
          ctest --output-on-failure || true
          lcov --capture --directory . --output-file coverage.info --ignore-errors source,negative
          lcov --remove coverage.info '/usr/*' 'tests/*' --output-file coverage.info --ignore-errors source,negative
          genhtml coverage.info --output-directory coverage-html
          mkdir -p ../coverage-html/arch
          cp -r coverage-html/* ../coverage-html/arch/
          cd ..
          useradd -m builder
          chown -R builder:builder .
          cd packaging/arch
          su builder -c "makepkg --noconfirm --clean --syncdeps"

      - name: Upload Arch package
        uses: actions/upload-artifact@v4
        with:
          name: arch-packages
          path: packaging/arch/*.pkg.tar.zst

  upload-coverage:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-arch]
    steps:
      - uses: actions/checkout@v4
      - name: Collect coverage
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Upload merged coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: artifacts/**/coverage-html
